name : Quality

# TRIGGER
on: [pull_request]

# JOBS
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo check
      - run: cargo fmt -- --check
      - run: cargo clippy --
      - run: cargo test
