name: test.yml
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache build artifacts
        id: cache-rust-target
        uses: actions/cache@v4
        with:
          path: |
            **/target
          key: cache-rust-target-${{ hashFiles('Cargo.lock') }}
      - uses: actions/checkout@v4
      - name: Run Back
        run: |
          cargo run &
          sleep 45
      - name: Test
        run: python example/test_functional.py
