#name: test.yml
#on:
#  pull_request:
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Cache cargo registry and build
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#      - name: Build Rust
#        run: cargo build
#      - name: Run Back
#        run: |
#          cargo run &
#          until nc -z localhost 8080; do sleep 1; done
#      - name: Test
#        run: python example/test_functional.py