name: Invalid PR

on:
  pull_request_target:
    types: [opened]
    branches:
      - 'releases/**'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      write-all
    steps:
      - name: Vérifier la branche source
        id: check_branch
        run: |
          if [[ "${{ github.head_ref }}" == "main" || "${{ github.head_ref }}" == bug/* ]]; then
            echo "ok=true" >> $GITHUB_OUTPUT
          else
            echo "ok=false" >> $GITHUB_OUTPUT
          fi
      - name: Fermer la PR si branche source invalide
        if: steps.check_branch.outputs.ok == 'false'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "La branche source doit être 'main' ou commencer par 'bug/'."
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Hash et message du commit dans les variables d'environnement
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Publier la release automatiquement
        uses: mini-bomba/create-github-release@v1.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          prerelease: true
          name: "Latest Commit, that compiles"
          body: |
            This automatic prerelease is built from commit ${{ env.GIT_HASH }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Message du commit :
            ${{ env.GIT_MESSAGE }}
          files: |
            build/*.exe
          clear_attachments: true
