name: Workflow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - name: Build avec Makefile
        run: make build
      - name: Build documentation
        run: make manual
      - name: Check code style
        run: make check
      - name: Format code
        run: make format