name: Deploiement SIMEIS

on:
  push:
    tags:
      - 'v*.*.*'  # Ex: v1.0.0, v1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deb_name: ${{ steps.build_deb.outputs.deb_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev gzip

      - name: Compiler le projet
        run: cargo build --release

      - name: Préparer le paquet
        run: |
          mkdir -p package/usr/bin
          mkdir -p package/usr/share/man/man1
          mkdir -p package/etc/systemd/system
          mkdir -p package/DEBIAN

          cp target/release/simeis-server package/usr/bin/
          cp propulse-ton-pere.1 package/usr/share/man/man1/
          gzip -f package/usr/share/man/man1/propulse-ton-pere.1
          cp simeis.service package/etc/systemd/system/
          cp packaging/control package/DEBIAN/
          cp packaging/preinst package/DEBIAN/
          cp packaging/postinst package/DEBIAN/
          chmod 755 package/DEBIAN/preinst package/DEBIAN/postinst

      - id: build_deb
        name: Construire le .deb
        run: |
          dpkg-deb --build package simeis_${{ github.ref_name }}.deb
          echo "deb_name=simeis_${{ github.ref_name }}.deb" >> "$GITHUB_OUTPUT"

      - name: Uploader l'artefact
        uses: actions/upload-artifact@v4
        with:
          name: simeis-deb
          path: simeis_${{ github.ref_name }}.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Télécharger l'artefact
        uses: actions/download-artifact@v4
        with:
          name: simeis-deb
          path: ./release-assets

      - name: Créer une release GitHub avec le .deb
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*.deb
